"""Create Customers, Transactions, Accounts, TokenBlockList models

Revision ID: 6160d9dcfd25
Revises: 
Create Date: 2022-08-11 22:30:47.105893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6160d9dcfd25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_block_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_block_list_jti'), 'token_block_list', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_block_list_jti'), table_name='token_block_list')
    op.drop_table('token_block_list')
    # ### end Alembic commands ###
